### ISSUE TITLE
【Playground】需更新版本

### ISSUE THREAD

**Issue by YangFong** [dream-num/univer-docs#96]
全局，右键菜单层级问题，需要更新包至 `0.1.2`，可见：https://univer.ai/playground/?title=Vite

<img width="1108" alt="image" src="https://github.com/dream-num/univer-docs/assets/70502828/ea535832-9447-4fb4-a6b1-0f0bf6e41946">

---

可见：https://univer.ai/playground/?title=React%20and%20Facade%20API

<img width="1676" alt="image" src="https://github.com/dream-num/univer-docs/assets/70502828/2e30d697-e4d4-4f3c-9606-53b275d44a5d">

**Comment by jikkai** [comment]
Thanks for your feedback. The demo will update automatically.
